server:
    port: 8888

#spring
spring:
    datasource:
        url: jdbc:mysql://192.168.220.128:3306/test
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456

mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.example.pojo.Student

